### ISSUE TITLE
Support CLI args?

### ISSUE THREAD

**Issue by AlJohri** [Tatsh/jxa-lib#7]
Does your webpack configuration for `jxa-lib` allow keeping the `run` function global for passing in CLI arguments?

This library for example has a webpack [config](https://github.com/pahund/patricks-little-jxa-helpers/blob/master/webpack.config.js) file + custom webpack [plugin](https://github.com/pahund/patricks-little-jxa-helpers/blob/master/src/plugin/jxa-plugin.js) that allows for this: https://github.com/pahund/patricks-little-jxa-helpers

The entire module gets set to `main` and then the global run function gets defined as such: `function run(args) { this.main(args); }`.

**Comment by AlJohri** [comment]
Config: https://github.com/pahund/patricks-little-jxa-helpers/blob/be0584e9c01399e01bccc8dd0c5acc1cfb9abe12/webpack.config.js#L30-L32

Plugin: https://github.com/pahund/patricks-little-jxa-helpers/blob/be0584e9c01399e01bccc8dd0c5acc1cfb9abe12/src/plugin/jxa-plugin.js#L12-L20

**Comment by Tatsh** [comment]
My Webpack config file is only for the [examples](https://github.com/Tatsh/jxa-lib/tree/master/examples) code. It should not affect anyone else's compilation process.

The examples code lacks a `run()` function because it doesn't take any CLI arguments.

**Comment by AlJohri** [comment]
Got it. I was a little confused how to actually get started using the library. I got by without it for now by manually parsing the CLI args instead of using an external library: https://github.com/AlJohri/outlook-apple-calendar-sync/blob/master/README.md

I’ll definitely try this out in my next JXA endeavor. I mainly want to easily leverage other libraries without losing CLI access and make the code less verbose.

If you could set up one example in a completely separate repo with this library installed that might make things a little easier.

Thanks for your work on this!
